import {
  Anchor,
  BaseBall,
  BezierCurve,
  Exam,
  ExcellLogo,
  Exclude,
  Globe,
  Home,
  HourGlass,
  HouseLine,
  IdentificationBadge,
  IdentificationCard,
  ImageSquare,
  IntersectSquare,
  Ladder,
  Leaf,
  ListPlus,
  Microphone,
  NotePad,
  NumberFive,
  NumberSeven,
  Orange,
  Paper,
  Peace,
  Pencil,
  Plus,
  Question,
  Road,
  Vignette,
  Watch,
} from "../icons";

export const icons = [
  { icon: <Home /> },
  { icon: <HouseLine /> },
  { icon: <IdentificationBadge /> },
  { icon: <IdentificationCard /> },
  { icon: <Ladder /> },
  { icon: <IntersectSquare /> },
  { icon: <ImageSquare /> },
  { icon: <Plus /> },
  { icon: <Microphone /> },
  { icon: <ExcellLogo /> },
  { icon: <NotePad /> },
  { icon: <ListPlus /> },
  { icon: <Leaf /> },
  { icon: <NumberFive /> },
  { icon: <NumberSeven /> },
  { icon: <Road /> },
  { icon: <HourGlass /> },
  { icon: <Anchor /> },
  { icon: <BezierCurve /> },
  { icon: <Exclude /> },
  { icon: <Vignette /> },
  { icon: <BaseBall /> },
  { icon: <Question /> },
  { icon: <Exam /> },
  { icon: <Watch /> },
  { icon: <Globe /> },
  { icon: <Orange /> },
  { icon: <Peace /> },
  { icon: <Paper /> },
  { icon: <Pencil /> },
];

export const colors = [
  { color: "#0166FF" },
  { color: "#01B3FF" },
  { color: "#41CC00" },
  { color: "#F9D100" },
  { color: "#FF7B01" },
  { color: "#AE01FF" },
  { color: "#FF0101" },
];
